const hisarZones = [
  "Aggarwal Colony",
  "Azad Nagar",
  "Barwala Road",
  "Bhiwani Road",
  "Camp Chowk",
  "Chawla Colony",
  "Dabra Chowk",
  "Dayanand Colony",
  "Defense Colony",
  "Dev Nagar",
  "Dharamshala Road",
  "Friends Colony",
  "Gandhi Nagar",
  "Geeta Colony",
  "Green Park",
  "Grewal Colony",
  "Huda Sector 13",
  "Huda Sector 14",
  "Jawahar Nagar",
  "Kaimri Road",
  "Kamla Nagar",
  "Krishna Nagar",
  "Lajpat Nagar",
  "Model Town",
  "Nehru Palace",
  "Old Court Complex",
  "Old Subzi Mandi",
  "Patel Nagar",
  "Prem Nagar",
  "Rishi Nagar",
  "Rajgarh Road",
  "Rishi Market",
  "Railway Road",
  "Ram Nagar",
  "Sanjay Nagar",
  "Shastri Nagar",
  "Shiv Nagar",
  "Subhash Nagar",
  "Sector 15",
  "Sector 16",
  "Sector 9-11",
  "Urban Estate I",
  "Urban Estate II",
  "Vikas Nagar",
  "Vishwakarma Colony",
  "Vishal Nagar"
];

module.exports=hisarZones
